### ISSUE TITLE
`group` and `groupToMap`  why not merge into one api

### ISSUE THREAD

**Issue by c0dedance** [tc39/proposal-array-grouping#43]
`group` and `groupToMap`  why not merge into one api, I think the implementation of the latter includes the former

**Comment by ljharb** [comment]
How would you specify that you wanted an object vs a Map, if it was in a single API?

**Comment by jimmywarting** [comment]
I'm questioning weather or not groupToMap is really necessary... it seems pretty easy to just use `slice` if you need a new copy...

`[].slice().group(...)`

**Comment by Andrew-Cottrell** [comment]
`group(...)` evaluates to a plain object rather than a `Map` (see [examples](https://github.com/tc39/proposal-array-grouping#proposal-array-grouping)).

`slice()` is unnecessary here as `group` and `groupToMap` do not modify the original array.

**Comment by michaelficarra** [comment]
I guess in theory we could have a single API which produces "entries" (an array of pairs) and then that could be passed to either `Object.fromEntries` or `new Map` (or maybe others) depending on the desired use.

**Comment by zloirock** [comment]
@michaelficarra how do you propose to handle keys?
```js
Object.keys(['1', 1, { valueOf() { return 1 } }].group(it => it)).length; // => 1
['1', 1, { valueOf() { return 1 } }].groupToMap(it => it).size; // => 3
```

**Comment by bakkot** [comment]
This has already been discussed at some length in https://github.com/tc39/proposal-array-grouping/issues/3. For the `entries` suggestion, see in particular [this comment](https://github.com/tc39/proposal-array-grouping/issues/3#issuecomment-888735688) and the few preceding it: you can't produce entries without know if you are producing entries-as-for-object or entries-as-for-Map, because you don't know if `"1"` and `1` should be treated as being the same group.

If you want entries, [make a `Map` and iterate it](https://github.com/tc39/proposal-array-grouping/issues/3#issuecomment-888040507).
